pages/installment.tsx
pages/views/InstallmentCalculator.jsx
pages/views/InstallmentInput.jsx
pages/views/NavBar.jsx
styles/Installment.module.css

This pull request addresses #6 , add Installment page. 
1. [added files] `pages/installment.tsx` , `pages/views/InstallmentCalculator.jsx` , `pages/views/InstallmentInput.jsx` , `styles/Installment.module.css`.
2. [modified code] `pages/views/NavBar.jsx`
I have tested these feature by manual testing.
1. Change `Amount` , `Interest Rate` , `Installment` number
2. Click `Calculate` button, it will compare plan a and plan b.
3. Show the best plan for you!

Feature: Add Installment page

---

pages/views/Rebalancer.jsx
pages/views/UserBalanceInfo.jsx
utils/rebalanceSuggestions.js

- **Bugfix**
the `monthly interest` used to be showing @david30907d 's personal monthly interest, the design was not for users. Therefore the current value is wrong

[fix](monthly interest): monthly interest should cal by user's deposit

---

pages/basePage.tsx
pages/views/Header.jsx
pages/views/NavBar.jsx
styles/Home.module.css
styles/index.scss

- **Other** (UI/UX)
Sometimes, the menu will be displayed as "...".
When clicking the menu icon on mobile, the way the menu is displayed is not normal.

[UI/UX](Menu):Fix navbar rwd

---

pages/views/ZapInButton.jsx

- **New feature** Add approve status icon
Display for the 'Approve' action with the following 4 states:
1. default: The default state, before the loading state (gray rotating circle).
2. loading:  Awaiting confirmation of the transaction (blue rotating circle).
3. success: The transaction has been successfully processed and confirmed by the blockchain network (primary color checkmark circle).
4. error: An error happened (warning color exclamation mark circle).
Use **wagmi** [useWaitForTransaction](https://wagmi.sh/react/hooks/useWaitForTransaction) Hook

[Feature] Approve status icon

---

README.md
pages/views/Rebalancer.jsx
pages/views/UserBalanceInfo.jsx
pages/views/Web3DataProvider.jsx
pages/views/ZapInButton.jsx

- **Other** (Deploy)
Merge `main` branch to `prod` branch

[Deploy] merge main to prod

---

pages/dashboard.tsx

[feat](dashboard): add a new POC page

---

pages/views/ZapInButton.jsx
pages/views/ZapOutButton.jsx
pages/views/components/SlippageModal.jsx
styles/index.scss
styles/zapInOut.module.scss

- **New feature** Slippage Settings
This enhancement focuses on improving the user experience by allowing users to customize slippage tolerance according to their preferences.

[Feature] Slippage Settings

---

pages/dashboard.tsx
utils/tableExpansionUtils.js

[feat](dashboard): accidentally drop the search dashboard

---

pages/dashboard.tsx

[fix](typescript): fix type errors

---

pages/views/SuggestionsForBetterStableCoins.jsx
pages/views/SuggestionsForLPTokens.jsx

[fix](better pools): rename the coin to tokens

---

utils/tableExpansionUtils.js

[fix](pools): remove *100 since the unit has changed on the backend side

---

pages/dashboard.tsx

- **Bugfix**
typescript need more type annotations

[fix](typescript): add some types for compiling

---

pages/dashboard.tsx

[refactor](dashboard): reuse the onSelect func

---

pages/dashboard.tsx

Fix unique tokens

---

utils/tableExpansionUtils.js

[feat](pool): add badge for APR predictions

---

pages/views/UserBalanceInfo.jsx
pages/views/Web3DataProvider.jsx
utils/rebalanceSuggestions.js

[feat](claimalbe rewards): show the claimable rewards for your portfolio

---

pages/dashboard.tsx
utils/tableExpansionUtils.js

[feat](dashboard): whitelist teammates

---

pages/dashboard.tsx

[fix](/dashboard): fix the whitelist module

---

pages/views/TopNLowestAprPools.jsx
utils/tableExpansionUtils.jsx

[fix]: backward compatibility

---

pages/views/TopNLowestAprPools.jsx
utils/tableExpansionUtils.jsx

Reverts all-weather-protocol/all-weather-frontend#75

Revert "[fix]: backward compatibility"

---

.github/workflows/lint.yaml
.gitignore
package.json
pages/basePage.tsx
pages/views/NavBar.jsx
vitest.config.js
yarn.lock

[feat](Vitest): unit test

---

pages/basePage.tsx
vitest.config.js

- **CI**
run `yarn format` to fix it

[format]: just run yarn format

---

pages/views/Performance.jsx

- **Bugfix**
since I changed the return on the backend side, we need to change the frontend accordingly

[fix](performance): fix historical chart

---

pages/views/Performance.jsx

[fixCI]: fix compiling issue

---

pages/views/Performance.jsx

[fixCI]: fix compiling

---

pages/views/Performance.jsx

[fixCI]: fleek

---

pages/basePage.tsx

[fix](rainbowkit): add connectors for wagmiconfig (#92)

---

lib/contracts/CamelotNFTPositionManager.json
pages/_app.tsx
pages/dashboard.tsx
pages/liquidityPoolRangeMonitoring.tsx
pages/views/NavBar.jsx

[wip](liquidity monitor): wip

---

.github/workflows/vitest.yaml
.gitignore
README.md
__tests__/basepage.test.jsx
package.json
vitest.config.js
yarn.lock

Add `vitest.yaml` for Git Actions. Add unit test template.

[feat](vitest): add vitest yaml and template

---

pages/views/RebalanceChart.jsx

[chores](chart): chores-update-according-to-backend-changes

---

pages/dashboard.tsx

- **Bugfix**
The dashboard page table can't select all options.

[fix](dashboard): fix table rowSelection selectAll bug

---

pages/views/APRPopOver.jsx
pages/views/Web3DataProvider.jsx
utils/contractInteractions.js
utils/rebalanceSuggestions.js

the flag `worksheet` is related to retrieving the latest Debank data

[feat](worksheet): add this flag for the upcoming gcs caching feature

---

pages/liquidityPoolRangeMonitoring.tsx

[feat](liquidity_pool): use worksheet to get the latest debank data

---

pages/liquidityPoolRangeMonitoring.tsx

[fix](liquidity pool range): add refresh flag

---

__tests__/basepage.test.jsx
__tests__/dashboard.test.jsx
package.json
yarn.lock

[fixCI]: test vitest

---

__tests__/basepage.test.jsx
__tests__/dashboard.test.jsx
package.json
pages/liquidityPoolRangeMonitoring.tsx
yarn.lock

[fix]: fix building issue

---

pages/views/RebalanceChart.jsx
pages/views/Strategy.jsx

[fix](/strategy): fix the sunburst chart with categories

---

utils/tableExpansionUtils.jsx

[chores]: add adrian's wallet into whitelist

---

pages/_app.tsx

[fix](build): fix building issue

---

pages/_app.tsx
pages/basePage.tsx
pages/views/ClaimButton.jsx
pages/views/Header.jsx
pages/views/Rebalancer.jsx
pages/views/Web3DataProvider.jsx
pages/views/ZapInButton.jsx
pages/views/ZapOutButton.jsx

Update `Rainbow` , `wagmi`, `viem` package。

Feature new wagmi

---

pages/dashboard.tsx
yarn.lock

[fix](fleek): type issue of typescript

---

pages/views/ZapInButton.jsx
pages/views/ZapOutButton.jsx
utils/contractInteractions.jsx

[fix]: use ? to pass typescript issue

---

pages/views/ZapInButton.jsx

[chores]: urger, disable deposit due to the exploit issue

---

.github/workflows/vitest.yaml
classes/AllWeatherPortfolio.js

[fix]: the API hostname accidentally became localhost

---

pages/dashboard.tsx
pages/views/components/LinkModal.jsx
utils/tableExpansionUtils.jsx

- **Other (Deploy)**
Merge `main` branch to `prod` branch

Fix dashboard dexlink build failed (#164)

---

pages/_app.tsx

[config](thirdweb): add thirdweb provider

---

pages/_app.tsx

Reverts all-weather-protocol/all-weather-frontend#173

Revert "[config](thirdweb): add thirdweb provider"

---

README.md
package.json
pages/_app.tsx
pages/basePage.tsx
pages/betterPools.tsx
pages/dashboard.tsx
pages/liquidityPoolRangeMonitoring.tsx
pages/views/APRPopOver.jsx
pages/views/Assets.jsx
pages/views/ClaimButton.jsx
pages/views/DOMforCefi.jsx
pages/views/DOMforCefiUsers.jsx
pages/views/ExampleUI.jsx
pages/views/HistoricalDataChart.jsx
pages/views/NavBar.jsx
pages/views/PortfolioMetaTab.jsx
pages/views/Rebalancer.jsx
pages/views/Strategy.jsx
pages/views/TokenDropdownInput.jsx
pages/views/UserBalanceInfo.jsx
pages/views/Web3DataProvider.jsx
pages/views/ZapInButton.jsx
pages/views/ZapOutButton.jsx
utils/betterPoolsMetadata.js
utils/rebalanceSuggestions.js
utils/tableExpansionUtils.jsx
yarn.lock

Reverts all-weather-protocol/all-weather-frontend#187

Revert "Feat/thirdweb embedded"

---

.prettierignore
package.json
pages/dashboard.tsx

[linter]: do ts-nocheck for the entire file

---

.github/pull_request_template.md

[docs]: update checklist

---

pages/dashboard.tsx

- **Bugfix**
There is an "unlock" button inside the table. When clicked, it should redirect to the "/subscription" page.

[fix](dashboard): fixed "unlock" button link to "/subscription" page

---

pages/views/Strategy.jsx
utils/rebalanceSuggestions.js

[fix](strategy): fix the data of rebalanceSuggestions

---

.github/workflows/lint.yaml

[ci](build): check whether its build process work or not

---

pages/subscription/index.jsx

[chores]: add basePage for subscription page

---

pages/basePage.tsx

[fix](autoconnect): need to add rabby and pahtong

---

.github/workflows/vitest.yaml
README.md
__tests__/dashboard.test.jsx
__tests__/test-utils.tsx
package.json
vitest.config.js
yarn.lock

測試是否能把 fetch 後拿到的 data render 到 view 上

[feat]: dashboard mock fetch data tests

---

pages/dashboard.tsx

[feat](dashboard): add scroll feature for specific section

---

pages/dashboard.tsx

Reverts all-weather-protocol/all-weather-frontend#212

Revert "[feat](dashboard): add scroll feature for specific section"

---

pages/dashboard.tsx

Reverts all-weather-protocol/all-weather-frontend#214

Revert "Revert "[feat](dashboard): add scroll feature for specific section""

---

pages/views/ClaimButton.jsx

[hotFIx]: comment out claim for DDOS

---

__tests__/rebalanceChart.test.js
pages/views/RebalanceChart.jsx

[fixCI]: try to fix

---

funding.json  

[config]: add this file for OP grant

---

components/tabs/ZapInTab.jsx

[poop]: we do this for Sun, will revert it afterward

---

components/tabs/ZapInTab.jsx
pages/Modal/index.jsx
pages/emailsubscription/index.jsx

[feat](steps): useblue and optimize UI

---

components/common/ActionItem.jsx
components/tabs/RebalanceTab.jsx
components/tabs/ZapInTab.jsx
components/tabs/ZapOutTab.jsx
pages/Modal/index.jsx

[feat](steps): use the current chain as the first action item

---

components/tabs/ZapInTab.jsx

Reverts all-weather-protocol/all-weather-frontend#795

Revert "[poop]: we do this for Sun, will revert it afterward"

---

components/tabs/ZapInTab.jsx

[chores]: for sun again

---

classes/BasePortfolio.jsx
components/tabs/RebalanceTab.jsx
hooks/useTabItems.jsx
pages/Modal/index.jsx

[feat](rebalance): improve rebalance button and flowchart's UI

---

classes/Vaults/StablecoinVault.jsx
components/CompletionActions.jsx
components/common/ActionItem.jsx
components/tabs/RebalanceTab.jsx
components/tabs/ZapInTab.jsx
components/tabs/ZapOutTab.jsx
hooks/useTabItems.jsx
pages/Modal/index.jsx
pages/indexes/indexOverviews.jsx
utils/environment.js

Feat/flowchart UI improvement

---

components/tabs/ZapInTab.jsx
pages/views/ExampleUI.jsx

[chores]: update example

---

__tests__/intent/convex.test.js
classes/Vaults/StablecoinVault.jsx
config/content.js
hooks/useTabItems.jsx
pages/indexes/indexOverviews.jsx
pages/indexes/transactionHistory.jsx
utils/transactionHelpers.js

[chores]: removed unused loading + add rebalanceDictLoading back

[fix]: txn history's fallback + use kelly's allocation

---

pages/indexes/indexOverviews.jsx

[fix]: chain weight is not correct

---

pages/indexes/indexOverviews.jsx

[ci]: format

---

__tests__/intent/camelot.test.js
classes/BasePortfolio.jsx
pages/indexes/indexOverviews.jsx
utils/localStorage.js
utils/swapHelper.js

[fix](cache): use backend API + cloud storage to cache the data

---

classes/Velodrome/BaseVelodrome.js

[fix](velodrome): use bigint to handle overflow

---

pages/indexes/indexOverviews.jsx

[fix](cache): use delete cache to update gcs cache

---

.prettierignore
__tests__/exampleUI.test.jsx
pages/portfolio/components/CategoryHeader.jsx

[fix]: img path not found

---

__tests__/intent/usdtzapin.test.js
classes/BasePortfolio.jsx
pages/indexes/indexOverviews.jsx

[fixCI](squid): fix the squid bridge test

---

classes/BasePortfolio.jsx
classes/BaseProtocol.js
classes/Pendle/BasePendlePT.js
classes/Vaults/Index500Vault.jsx
classes/Vaults/StablecoinVault.jsx
classes/bridges/bridgeFactory.ts

[feat](pendle): implemented PT pool

---

pages/indexes/indexOverviews.jsx
utils/chainHelper.js
utils/chainOrder.js

[refactor]: deprecate switchChain old logic

---

classes/BasePortfolio.jsx
pages/indexes/indexOverviews.jsx
utils/transactionErrorHandler.js

[feat](log): show actionParams at the notification

---

classes/Vaults/EthVault.jsx

[chores](eth vault): use pendle to replace equilibria

---

utils/swapHelper.js

[fix]: hot fix

---

classes/BasePortfolio.jsx
hooks/useTabItems.jsx
pages/indexes/indexOverviews.jsx
pages/profile/index.jsx

[fix](rebalance APR): fix those missing APR and NaN rebalance APR

---

.gitignore
next.config.js
package.json
pages/_document.js
public/manifest.json
yarn.lock

[feat](pwa): test PWA page

---

.github/workflows/sync-to-staging.yml
config/minimumThresholds.js

[fixCI]: fix sync repo action

---

CLAUDE.md
README.md

- Add CLAUDE.md with detailed guidance for AI-assisted development
- Restructure README.md with expanded architecture overview
- Document protocol integration workflows and testing guidelines
- Add development commands reference and deployment information
- Improve onboarding documentation for new developers

docs: Add comprehensive development documentation and restructure README

---

.github/workflows/sync-to-staging.yml

[chores]: update ci pipeline

---

.github/workflows/sync-to-staging.yml

[fix]: fix branch issue

---

.github/workflows/sync-to-staging.yml

[chores]: test

---

.cursorignore
components/tabs/ConvertDustTab.jsx
pages/indexes/indexOverviews.jsx
utils/dustConversion.js
utils/slippage.js

- Remove console.log statements from ConvertDustTab and indexOverviews
- Add .cursorignore for large asset directories
- Improve slippage handling:
- Add manual slippage control
- Persist user's slippage choice
- Update slippage options range (0.5-50%)
- Increase test coverage requirement from 3% to 40%
- Fix JSON formatting in package.json

chore: cleanup code and improve test coverage

---

utils/contractInteractions.jsx

[fix](token price): need to fetch these price for new vault

---

.claude/commands/testcases.md
__tests__/classes/BaseAura.test.js
__tests__/classes/FlowChartMixin.test.js
__tests__/classes/Vela.test.js
__tests__/classes/YearnV3Vault.test.js
vitest.config.js

- Comprehensive mocking of external dependencies
- Error handling scenarios
- Edge case testing
- Integration testing patterns
- Proper isolation and cleanup

The test cases added follow best practices including:

---

classes/BasePortfolio.jsx

feat: remove fee feature from rebalance

---

pages/contextWrappers/WalletModeContext.jsx
pages/dustzap/index.jsx

fix: move the fee charing txns to the end of the batch

---

components/tabs/TransferTab.jsx

feat: add stake btn for transfer

---

hooks/useTabItems.jsx

chores: remove dustTab

---

FRAME_TESTING.md
__tests__/frames/dustzapFrame.test.js
__tests__/frames/frameAPI.test.js
__tests__/frames/frameImage.test.js
package.json
pages/api/frames/dustzap.ts
pages/api/frames/image.tsx
pages/frames/dustzap.tsx
scripts/test-frame.sh
yarn.lock

feat(farcaster): create iframe

---

components/dustzap/SlippageSelector.jsx
pages/dustzap/index.jsx

fix: use 49% as default slippage

---

classes/BaseProtocol.js
pages/dustzap/index.jsx

fix: fix eth amount of dust zap

---

classes/Vaults/StablecoinVault.jsx

chores: add new pendle pt pools
